/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/ishell/lib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

// Progress 结构体（C 兼容）
typedef struct {
	int64_t transferred;
	int64_t total;
	double percent;
} ZmodemProgress;

// Status 结构体（C 兼容）
typedef struct {
	int status;      // 0=idle, 1=active, 2=completed, 3=error
	char* message;   // 错误消息（如果 status=3）
} ZmodemStatus;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// ZmodemInit 初始化 ZMODEM 会话
// mode: 0=upload (rz), 1=download (sz)
// filePath: 文件路径
// 返回: session_id (>=0) 或 -1 表示失败
//
extern int ZmodemInit(int mode, char* filePath);

// ZmodemFeedData 输入数据（从 SSH channel 接收）
// sessionId: 会话 ID
// data: 数据指针
// dataLen: 数据长度
// 返回: 0=成功, -1=错误
//
extern int ZmodemFeedData(int sessionId, uint8_t* data, int dataLen);

// ZmodemGetOutputData 获取输出数据（需要发送到 SSH channel）
// sessionId: 会话 ID
// buffer: 输出缓冲区
// bufferLen: 缓冲区长度
// 返回: 实际数据长度 (>=0), 0=无数据, -1=错误
//
extern int ZmodemGetOutputData(int sessionId, uint8_t* buffer, int bufferLen);

// ZmodemGetProgress 获取传输进度
// sessionId: 会话 ID
// 返回: Progress 结构体指针（需要调用者 free），nil 表示错误
//
extern ZmodemProgress* ZmodemGetProgress(int sessionId);

// ZmodemFreeProgress 释放 Progress 结构体内存
//
extern void ZmodemFreeProgress(ZmodemProgress* progress);

// ZmodemGetStatus 获取会话状态
// sessionId: 会话 ID
// 返回: Status 结构体指针（需要调用者 free），nil 表示错误
//
extern ZmodemStatus* ZmodemGetStatus(int sessionId);

// ZmodemFreeStatus 释放 Status 结构体内存
//
extern void ZmodemFreeStatus(ZmodemStatus* status);

// ZmodemCleanup 清理会话资源
// sessionId: 会话 ID
//
extern void ZmodemCleanup(int sessionId);

#ifdef __cplusplus
}
#endif
